package com.tothenew.bootcamp.enums;


public enum StatusCode {
    SUCCESS,
    FAILED,
    PENDING,
    NOT_VALID_FORMAT,
    ALREADY_REGISTERED,
    BAD_CREDENTIALS,
    NOT_PROVIDED,
    FIELD_MISSING,
    NOT_REGISTERED,
    ACCOUNT_DEACTIVATED,
    ACCOUNT_DELETED,
    ACCOUNT_ACTIVATED,
    LINK_GENERATED,
    PASSWORD_RESET,
    ACTIVATION,
    TOKEN_EXPIRED,
    SESSION_EXPIRED,
    TOKEN_INVALID,
    PASSWORD_MISMATCH,
    OLD_PASSWORD_MISMATCH,
    NEW_PASSWORD_MISMATCH,
    EMPTY,
    DOES_NOT_EXIST


}


